---
- name: 'Clone the zfs fedora installer repo'
  git:
    repo: '{{ repo_url }}'
    dest: '{{ repo_dir  }}'

- name: Run the deploy-zfs script
  shell: deploy-zfs
  args:
    chdir: '{{ repo_dir  }}'
