---
- name: 'Identify the rpm distribution'
  shell: rpm -E %dist
  register: rpm_dist

- name: 'Install repo details for zfs'
  dnf:
    name: 'http://download.zfsonlinux.org/fedora/zfs-release{{ rpm_dist.stdout }}.noarch.rpm'
    disable_gpg_check: yes

- name: 'Install zfs system'
  dnf: 
    name: 'kernel-devel, zfs'
